#png(file="plot4.png", width=480, height=480)
temp <- tempfile()
download.file(url="https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", method="curl",temp)
data <- read.table(unz(temp, "household_power_consumption.txt"), sep=";", header=TRUE, na.strings='?')
unlink(temp)
data$Date<-as.Date(data$Date, format="%d/%m/%Y")
data.2007<-subset(data, Date >="2007-02-01" & Date <="2007-02-02")
vec<-strptime(paste(data.2007$Date, data.2007$Time), format="%Y-%m-%d %H:%M:%S")
par(mfrow=c(2,2))
with(data.2007, {
                plot(vec, Global_active_power, type='l', xlab="")
                plot(vec, Voltage, type='l', xlab="datetime", ylab="Voltage") 
                plot(vec, Sub_metering_1, type='n', xlab="", ylab="Energy sub metering") 
                lines(vec, Sub_metering_1, type='l', col="black") 
                lines(vec, Sub_metering_2, type='l', col="red")
                lines(vec, Sub_metering_3, type='l', col="blue")
                plot(vec, Global_reactive_power, type='l', xlab="datetime") 
})

legend("topright", col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=c(1,1,1))
dev.off()
