png(file="plot1.png", width=480, height=480)
temp <- tempfile()
download.file(url="https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", method="curl",temp)
data <- read.table(unz(temp, "household_power_consumption.txt"), sep=";", header=TRUE, na.strings='?')
unlink(temp)
data$Date<-as.Date(data$Date, format="%d/%m/%Y")
data.2007<-subset(data, Date >="2007-02-01" & Date <="2007-02-02")
hist(data.2007$Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", col="red")
dev.off()
